# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bring_your_own_png.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_bring_your_own_png(object):
    def setupUi(self, bring_your_own_png):
        bring_your_own_png.setObjectName("bring_your_own_png")
        bring_your_own_png.resize(857, 419)
        self.graphic_original = QtWidgets.QGraphicsView(bring_your_own_png)
        self.graphic_original.setGeometry(QtCore.QRect(10, 10, 191, 191))
        self.graphic_original.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_original.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_original.setSceneRect(QtCore.QRectF(0.0, 0.0, 100.0, 100.0))
        self.graphic_original.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphic_original.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemShape)
        self.graphic_original.setObjectName("graphic_original")
        self.graphic_prepared = QtWidgets.QGraphicsView(bring_your_own_png)
        self.graphic_prepared.setGeometry(QtCore.QRect(330, 10, 191, 191))
        self.graphic_prepared.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_prepared.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_prepared.setSceneRect(QtCore.QRectF(0.0, 0.0, 100.0, 100.0))
        self.graphic_prepared.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphic_prepared.setObjectName("graphic_prepared")
        self.graphic_svg_eu = QtWidgets.QGraphicsView(bring_your_own_png)
        self.graphic_svg_eu.setGeometry(QtCore.QRect(650, 10, 191, 191))
        self.graphic_svg_eu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_svg_eu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_svg_eu.setSceneRect(QtCore.QRectF(0.0, 0.0, 100.0, 100.0))
        self.graphic_svg_eu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphic_svg_eu.setObjectName("graphic_svg_eu")
        self.label_preparation = QtWidgets.QLabel(bring_your_own_png)
        self.label_preparation.setGeometry(QtCore.QRect(210, 40, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.label_preparation.setFont(font)
        self.label_preparation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_preparation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preparation.setIndent(0)
        self.label_preparation.setObjectName("label_preparation")
        self.label_autotrace = QtWidgets.QLabel(bring_your_own_png)
        self.label_autotrace.setGeometry(QtCore.QRect(520, 40, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.label_autotrace.setFont(font)
        self.label_autotrace.setAlignment(QtCore.Qt.AlignCenter)
        self.label_autotrace.setObjectName("label_autotrace")
        self.label_arrow = QtWidgets.QLabel(bring_your_own_png)
        self.label_arrow.setGeometry(QtCore.QRect(220, 70, 101, 61))
        self.label_arrow.setText("")
        self.label_arrow.setPixmap(QtGui.QPixmap("Arrow.png"))
        self.label_arrow.setScaledContents(True)
        self.label_arrow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arrow.setObjectName("label_arrow")
        self.button_autotrace = QtWidgets.QPushButton(bring_your_own_png)
        self.button_autotrace.setGeometry(QtCore.QRect(540, 80, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.button_autotrace.setFont(font)
        self.button_autotrace.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.button_autotrace.setObjectName("button_autotrace")
        self.prepa_slider_medianfilter = QtWidgets.QSlider(bring_your_own_png)
        self.prepa_slider_medianfilter.setGeometry(QtCore.QRect(10, 310, 160, 22))
        self.prepa_slider_medianfilter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.prepa_slider_medianfilter.setMaximum(20)
        self.prepa_slider_medianfilter.setPageStep(1)
        self.prepa_slider_medianfilter.setProperty("value", 1)
        self.prepa_slider_medianfilter.setSliderPosition(1)
        self.prepa_slider_medianfilter.setOrientation(QtCore.Qt.Horizontal)
        self.prepa_slider_medianfilter.setObjectName("prepa_slider_medianfilter")
        self.prepa_label_medianfilter = QtWidgets.QLabel(bring_your_own_png)
        self.prepa_label_medianfilter.setGeometry(QtCore.QRect(20, 280, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.prepa_label_medianfilter.setFont(font)
        self.prepa_label_medianfilter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prepa_label_medianfilter.setAlignment(QtCore.Qt.AlignCenter)
        self.prepa_label_medianfilter.setIndent(0)
        self.prepa_label_medianfilter.setObjectName("prepa_label_medianfilter")
        self.prepa_line_edit_medianfilter = QtWidgets.QLineEdit(bring_your_own_png)
        self.prepa_line_edit_medianfilter.setGeometry(QtCore.QRect(190, 310, 41, 20))
        self.prepa_line_edit_medianfilter.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.prepa_line_edit_medianfilter.setMaxLength(3)
        self.prepa_line_edit_medianfilter.setObjectName("prepa_line_edit_medianfilter")
        self.prepa_label_contrast = QtWidgets.QLabel(bring_your_own_png)
        self.prepa_label_contrast.setGeometry(QtCore.QRect(10, 350, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.prepa_label_contrast.setFont(font)
        self.prepa_label_contrast.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prepa_label_contrast.setAlignment(QtCore.Qt.AlignCenter)
        self.prepa_label_contrast.setIndent(0)
        self.prepa_label_contrast.setObjectName("prepa_label_contrast")
        self.prepa_slider_contrast = QtWidgets.QSlider(bring_your_own_png)
        self.prepa_slider_contrast.setGeometry(QtCore.QRect(10, 380, 160, 22))
        self.prepa_slider_contrast.setMaximum(120)
        self.prepa_slider_contrast.setProperty("value", 20)
        self.prepa_slider_contrast.setSliderPosition(20)
        self.prepa_slider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.prepa_slider_contrast.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.prepa_slider_contrast.setTickInterval(10)
        self.prepa_slider_contrast.setObjectName("prepa_slider_contrast")
        self.prepa_line_edit_contrast = QtWidgets.QLineEdit(bring_your_own_png)
        self.prepa_line_edit_contrast.setGeometry(QtCore.QRect(190, 380, 41, 20))
        self.prepa_line_edit_contrast.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.prepa_line_edit_contrast.setObjectName("prepa_line_edit_contrast")
        self.button_next = QtWidgets.QPushButton(bring_your_own_png)
        self.button_next.setGeometry(QtCore.QRect(530, 380, 75, 23))
        self.button_next.setObjectName("button_next")
        self.button_cancel = QtWidgets.QPushButton(bring_your_own_png)
        self.button_cancel.setGeometry(QtCore.QRect(420, 380, 75, 23))
        self.button_cancel.setTabletTracking(False)
        self.button_cancel.setObjectName("button_cancel")
        self.prepa_slider_despeckle = QtWidgets.QSlider(bring_your_own_png)
        self.prepa_slider_despeckle.setGeometry(QtCore.QRect(620, 240, 160, 22))
        self.prepa_slider_despeckle.setMinimum(1)
        self.prepa_slider_despeckle.setMaximum(100)
        self.prepa_slider_despeckle.setPageStep(1)
        self.prepa_slider_despeckle.setProperty("value", 55)
        self.prepa_slider_despeckle.setSliderPosition(55)
        self.prepa_slider_despeckle.setOrientation(QtCore.Qt.Horizontal)
        self.prepa_slider_despeckle.setObjectName("prepa_slider_despeckle")
        self.prepa_label_middle_color = QtWidgets.QLabel(bring_your_own_png)
        self.prepa_label_middle_color.setGeometry(QtCore.QRect(620, 220, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.prepa_label_middle_color.setFont(font)
        self.prepa_label_middle_color.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prepa_label_middle_color.setAlignment(QtCore.Qt.AlignCenter)
        self.prepa_label_middle_color.setIndent(0)
        self.prepa_label_middle_color.setObjectName("prepa_label_middle_color")
        self.prepa_line_edit_despeckle = QtWidgets.QLineEdit(bring_your_own_png)
        self.prepa_line_edit_despeckle.setGeometry(QtCore.QRect(800, 240, 41, 20))
        self.prepa_line_edit_despeckle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.prepa_line_edit_despeckle.setMaxLength(3)
        self.prepa_line_edit_despeckle.setObjectName("prepa_line_edit_despeckle")
        self.button_upsampling = QtWidgets.QPushButton(bring_your_own_png)
        self.button_upsampling.setGeometry(QtCore.QRect(10, 220, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.button_upsampling.setFont(font)
        self.button_upsampling.setCheckable(True)
        self.button_upsampling.setObjectName("button_upsampling")
        self.prepa_line_edit_errorthreshold = QtWidgets.QLineEdit(bring_your_own_png)
        self.prepa_line_edit_errorthreshold.setGeometry(QtCore.QRect(800, 290, 41, 20))
        self.prepa_line_edit_errorthreshold.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.prepa_line_edit_errorthreshold.setMaxLength(3)
        self.prepa_line_edit_errorthreshold.setObjectName("prepa_line_edit_errorthreshold")
        self.prepa_slider_errorthreshold = QtWidgets.QSlider(bring_your_own_png)
        self.prepa_slider_errorthreshold.setGeometry(QtCore.QRect(620, 290, 160, 22))
        self.prepa_slider_errorthreshold.setMinimum(1)
        self.prepa_slider_errorthreshold.setMaximum(100)
        self.prepa_slider_errorthreshold.setPageStep(1)
        self.prepa_slider_errorthreshold.setProperty("value", 10)
        self.prepa_slider_errorthreshold.setSliderPosition(10)
        self.prepa_slider_errorthreshold.setOrientation(QtCore.Qt.Horizontal)
        self.prepa_slider_errorthreshold.setObjectName("prepa_slider_errorthreshold")
        self.prepa_label_errorthreshold = QtWidgets.QLabel(bring_your_own_png)
        self.prepa_label_errorthreshold.setGeometry(QtCore.QRect(620, 270, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.prepa_label_errorthreshold.setFont(font)
        self.prepa_label_errorthreshold.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prepa_label_errorthreshold.setAlignment(QtCore.Qt.AlignCenter)
        self.prepa_label_errorthreshold.setIndent(0)
        self.prepa_label_errorthreshold.setObjectName("prepa_label_errorthreshold")
        self.prepa_slider_corner = QtWidgets.QSlider(bring_your_own_png)
        self.prepa_slider_corner.setGeometry(QtCore.QRect(620, 340, 160, 22))
        self.prepa_slider_corner.setMinimum(2)
        self.prepa_slider_corner.setMaximum(10)
        self.prepa_slider_corner.setPageStep(1)
        self.prepa_slider_corner.setProperty("value", 4)
        self.prepa_slider_corner.setSliderPosition(4)
        self.prepa_slider_corner.setOrientation(QtCore.Qt.Horizontal)
        self.prepa_slider_corner.setObjectName("prepa_slider_corner")
        self.prepa_line_edit_corner = QtWidgets.QLineEdit(bring_your_own_png)
        self.prepa_line_edit_corner.setGeometry(QtCore.QRect(800, 340, 41, 20))
        self.prepa_line_edit_corner.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.prepa_line_edit_corner.setMaxLength(3)
        self.prepa_line_edit_corner.setObjectName("prepa_line_edit_corner")
        self.prepa_label_corner = QtWidgets.QLabel(bring_your_own_png)
        self.prepa_label_corner.setGeometry(QtCore.QRect(620, 320, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.prepa_label_corner.setFont(font)
        self.prepa_label_corner.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prepa_label_corner.setAlignment(QtCore.Qt.AlignCenter)
        self.prepa_label_corner.setIndent(0)
        self.prepa_label_corner.setObjectName("prepa_label_corner")
        self.lineEdit_filename = QtWidgets.QLineEdit(bring_your_own_png)
        self.lineEdit_filename.setGeometry(QtCore.QRect(320, 250, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_filename.setFont(font)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.prepa_label_new_filename = QtWidgets.QLabel(bring_your_own_png)
        self.prepa_label_new_filename.setGeometry(QtCore.QRect(320, 220, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(14)
        self.prepa_label_new_filename.setFont(font)
        self.prepa_label_new_filename.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prepa_label_new_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.prepa_label_new_filename.setIndent(0)
        self.prepa_label_new_filename.setObjectName("prepa_label_new_filename")

        self.retranslateUi(bring_your_own_png)
        self.button_cancel.clicked.connect(bring_your_own_png.reject)
        self.button_next.clicked.connect(bring_your_own_png.accept)
        QtCore.QMetaObject.connectSlotsByName(bring_your_own_png)

    def retranslateUi(self, bring_your_own_png):
        _translate = QtCore.QCoreApplication.translate
        bring_your_own_png.setWindowTitle(_translate("bring_your_own_png", "Bring Your Own PNG"))
        self.graphic_original.setToolTip(_translate("bring_your_own_png", "Click to load a picture"))
        self.graphic_prepared.setToolTip(_translate("bring_your_own_png", "Use median filter and contrast to see a difference here"))
        self.graphic_svg_eu.setToolTip(_translate("bring_your_own_png", "Click on \"Try it\" to see your vector graphic here"))
        self.label_preparation.setText(_translate("bring_your_own_png", "Preparation"))
        self.label_autotrace.setText(_translate("bring_your_own_png", "Autotrace"))
        self.button_autotrace.setToolTip(_translate("bring_your_own_png", "Autotrace your picture to see the result"))
        self.button_autotrace.setText(_translate("bring_your_own_png", "Try it"))
        self.prepa_slider_medianfilter.setToolTip(_translate("bring_your_own_png", "Set the median filter to higher values to remove noise, or to lower values to preserve detail."))
        self.prepa_label_medianfilter.setText(_translate("bring_your_own_png", "Median Filter"))
        self.prepa_line_edit_medianfilter.setToolTip(_translate("bring_your_own_png", "Set the median filter to higher values to remove noise, or to lower values to preserve detail."))
        self.prepa_line_edit_medianfilter.setText(_translate("bring_your_own_png", "1"))
        self.prepa_label_contrast.setToolTip(_translate("bring_your_own_png", "To make your symbol really black and white, enhance contrast here"))
        self.prepa_label_contrast.setText(_translate("bring_your_own_png", "Contrast Enhancing"))
        self.prepa_slider_contrast.setToolTip(_translate("bring_your_own_png", "To make your symbol really black and white, enhance contrast here"))
        self.prepa_line_edit_contrast.setToolTip(_translate("bring_your_own_png", "To make your symbol really black and white, enhance contrast here"))
        self.prepa_line_edit_contrast.setText(_translate("bring_your_own_png", "20"))
        self.button_next.setText(_translate("bring_your_own_png", "next step"))
        self.button_cancel.setText(_translate("bring_your_own_png", "Cancel"))
        self.prepa_slider_despeckle.setToolTip(_translate("bring_your_own_png", "Set the mid point of the final color palette"))
        self.prepa_label_middle_color.setToolTip(_translate("bring_your_own_png", "Set the mid point of the final color palette"))
        self.prepa_label_middle_color.setText(_translate("bring_your_own_png", "Middle color"))
        self.prepa_line_edit_despeckle.setToolTip(_translate("bring_your_own_png", "Set the mid point of the final color palette"))
        self.prepa_line_edit_despeckle.setText(_translate("bring_your_own_png", "55"))
        self.button_upsampling.setText(_translate("bring_your_own_png", "Upsampling"))
        self.prepa_line_edit_errorthreshold.setToolTip(_translate("bring_your_own_png", "Accepts stranges lines on high values, deletes them on low values"))
        self.prepa_line_edit_errorthreshold.setText(_translate("bring_your_own_png", "10"))
        self.prepa_slider_errorthreshold.setToolTip(_translate("bring_your_own_png", "Accepts stranges lines on high values, deletes them on low values"))
        self.prepa_label_errorthreshold.setToolTip(_translate("bring_your_own_png", "Accepts stranges lines on high values, deletes them on low values"))
        self.prepa_label_errorthreshold.setText(_translate("bring_your_own_png", "Error Threshold"))
        self.prepa_slider_corner.setToolTip(_translate("bring_your_own_png", "How many pixels make a corner? More -> rounder Less -> mor corners"))
        self.prepa_line_edit_corner.setToolTip(_translate("bring_your_own_png", "How many pixels make a corner? More -> rounder Less -> mor corners"))
        self.prepa_line_edit_corner.setText(_translate("bring_your_own_png", "4"))
        self.prepa_label_corner.setToolTip(_translate("bring_your_own_png", "How many pixels make a corner? More -> rounder Less -> mor corners"))
        self.prepa_label_corner.setText(_translate("bring_your_own_png", "Corner Detect"))
        self.prepa_label_new_filename.setText(_translate("bring_your_own_png", "New Filename"))

