# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monstereditor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(578, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Icons/Base/Goblin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setToolTip("")
        Dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(370, 520, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.graphic_background = QtWidgets.QGraphicsView(Dialog)
        self.graphic_background.setGeometry(QtCore.QRect(30, 25, 280, 425))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(65, 255, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 255, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.graphic_background.setPalette(palette)
        self.graphic_background.setAcceptDrops(False)
        self.graphic_background.setToolTip("")
        self.graphic_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.graphic_background.setStyleSheet("font: 8pt \"HQModern\";")
        self.graphic_background.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphic_background.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphic_background.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_background.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_background.setInteractive(False)
        self.graphic_background.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphic_background.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphic_background.setObjectName("graphic_background")
        self.textEdit_name = QtWidgets.QTextEdit(Dialog)
        self.textEdit_name.setGeometry(QtCore.QRect(80, 38, 180, 29))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(140, 117, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 117, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit_name.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gaze")
        font.setPointSize(18)
        self.textEdit_name.setFont(font)
        self.textEdit_name.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit_name.setAutoFillBackground(False)
        self.textEdit_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_name.setLineWidth(-1)
        self.textEdit_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_name.setLineWrapColumnOrWidth(-4)
        self.textEdit_name.setObjectName("textEdit_name")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(89, 68, 162, 189))
        self.graphicsView.setToolTipDuration(-1)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setLineWidth(2)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 162.0, 189.0))
        self.graphicsView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphicsView.setObjectName("graphicsView")
        self.label_move = QtWidgets.QLabel(Dialog)
        self.label_move.setGeometry(QtCore.QRect(62, 260, 57, 16))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.label_move.setFont(font)
        self.label_move.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_move.setAlignment(QtCore.Qt.AlignCenter)
        self.label_move.setObjectName("label_move")
        self.label_at = QtWidgets.QLabel(Dialog)
        self.label_at.setGeometry(QtCore.QRect(110, 260, 41, 16))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.label_at.setFont(font)
        self.label_at.setAlignment(QtCore.Qt.AlignCenter)
        self.label_at.setObjectName("label_at")
        self.label_de = QtWidgets.QLabel(Dialog)
        self.label_de.setGeometry(QtCore.QRect(150, 260, 41, 16))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.label_de.setFont(font)
        self.label_de.setAlignment(QtCore.Qt.AlignCenter)
        self.label_de.setObjectName("label_de")
        self.label_bp = QtWidgets.QLabel(Dialog)
        self.label_bp.setGeometry(QtCore.QRect(190, 260, 41, 16))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.label_bp.setFont(font)
        self.label_bp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bp.setObjectName("label_bp")
        self.label_mp = QtWidgets.QLabel(Dialog)
        self.label_mp.setGeometry(QtCore.QRect(230, 260, 41, 16))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.label_mp.setFont(font)
        self.label_mp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mp.setObjectName("label_mp")
        self.plain_text_special_rules = QtWidgets.QPlainTextEdit(Dialog)
        self.plain_text_special_rules.setGeometry(QtCore.QRect(50, 329, 201, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(64, 115, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 115, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.plain_text_special_rules.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(10)
        self.plain_text_special_rules.setFont(font)
        self.plain_text_special_rules.setAcceptDrops(False)
        self.plain_text_special_rules.setAutoFillBackground(False)
        self.plain_text_special_rules.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plain_text_special_rules.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plain_text_special_rules.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_special_rules.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plain_text_special_rules.setBackgroundVisible(False)
        self.plain_text_special_rules.setObjectName("plain_text_special_rules")
        self.group_box_style = QtWidgets.QGroupBox(Dialog)
        self.group_box_style.setGeometry(QtCore.QRect(30, 480, 61, 71))
        self.group_box_style.setObjectName("group_box_style")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.group_box_style)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 41, 42))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radio_us = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_us.setObjectName("radio_us")
        self.verticalLayout_3.addWidget(self.radio_us)
        self.radio_eu = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_eu.setChecked(True)
        self.radio_eu.setObjectName("radio_eu")
        self.verticalLayout_3.addWidget(self.radio_eu)
        self.at_diagonal = QtWidgets.QCheckBox(Dialog)
        self.at_diagonal.setGeometry(QtCore.QRect(360, 40, 70, 17))
        self.at_diagonal.setObjectName("at_diagonal")
        self.at_ranged = QtWidgets.QCheckBox(Dialog)
        self.at_ranged.setGeometry(QtCore.QRect(360, 60, 70, 17))
        self.at_ranged.setObjectName("at_ranged")
        self.group_box_at_symbol = QtWidgets.QGroupBox(Dialog)
        self.group_box_at_symbol.setGeometry(QtCore.QRect(440, 30, 120, 101))
        self.group_box_at_symbol.setObjectName("group_box_at_symbol")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.group_box_at_symbol)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 111, 74))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_at_skull = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("skull.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio_at_skull.setIcon(icon1)
        self.radio_at_skull.setChecked(True)
        self.radio_at_skull.setObjectName("radio_at_skull")
        self.verticalLayout.addWidget(self.radio_at_skull)
        self.radio_at_shield = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("white-shield.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio_at_shield.setIcon(icon2)
        self.radio_at_shield.setObjectName("radio_at_shield")
        self.verticalLayout.addWidget(self.radio_at_shield)
        self.radio_at_walrus = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("black-shield.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radio_at_walrus.setIcon(icon3)
        self.radio_at_walrus.setObjectName("radio_at_walrus")
        self.verticalLayout.addWidget(self.radio_at_walrus)
        self.icon_topleft = QtWidgets.QGraphicsView(Dialog)
        self.icon_topleft.setGeometry(QtCore.QRect(40, 36, 40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.icon_topleft.setPalette(palette)
        self.icon_topleft.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.icon_topleft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.icon_topleft.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.icon_topleft.setObjectName("icon_topleft")
        self.icon_bottomright = QtWidgets.QGraphicsView(Dialog)
        self.icon_bottomright.setGeometry(QtCore.QRect(260, 400, 40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 94, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 94, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.icon_bottomright.setPalette(palette)
        self.icon_bottomright.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.icon_bottomright.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.icon_bottomright.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.icon_bottomright.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.icon_bottomright.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemBoundingRect)
        self.icon_bottomright.setObjectName("icon_bottomright")
        self.group_box_de_symbol = QtWidgets.QGroupBox(Dialog)
        self.group_box_de_symbol.setGeometry(QtCore.QRect(440, 230, 120, 101))
        self.group_box_de_symbol.setObjectName("group_box_de_symbol")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.group_box_de_symbol)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 111, 74))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radio_de_skull = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radio_de_skull.setIcon(icon1)
        self.radio_de_skull.setObjectName("radio_de_skull")
        self.verticalLayout_2.addWidget(self.radio_de_skull)
        self.radio_de_shield = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radio_de_shield.setIcon(icon2)
        self.radio_de_shield.setObjectName("radio_de_shield")
        self.verticalLayout_2.addWidget(self.radio_de_shield)
        self.radio_de_walrus = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radio_de_walrus.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.radio_de_walrus.setIcon(icon3)
        self.radio_de_walrus.setIconSize(QtCore.QSize(16, 16))
        self.radio_de_walrus.setChecked(True)
        self.radio_de_walrus.setAutoExclusive(True)
        self.radio_de_walrus.setObjectName("radio_de_walrus")
        self.verticalLayout_2.addWidget(self.radio_de_walrus)
        self.at_number = QtWidgets.QSpinBox(Dialog)
        self.at_number.setGeometry(QtCore.QRect(360, 120, 42, 22))
        self.at_number.setMaximum(20)
        self.at_number.setProperty("value", 1)
        self.at_number.setObjectName("at_number")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(360, 100, 51, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(360, 150, 91, 16))
        self.label_7.setObjectName("label_7")
        self.at_damage_type = QtWidgets.QPlainTextEdit(Dialog)
        self.at_damage_type.setGeometry(QtCore.QRect(360, 170, 171, 31))
        self.at_damage_type.setObjectName("at_damage_type")
        self.de_guardian = QtWidgets.QCheckBox(Dialog)
        self.de_guardian.setGeometry(QtCore.QRect(360, 240, 70, 17))
        self.de_guardian.setObjectName("de_guardian")
        self.de_master = QtWidgets.QCheckBox(Dialog)
        self.de_master.setGeometry(QtCore.QRect(360, 260, 69, 17))
        self.de_master.setObjectName("de_master")
        self.de_phalanx = QtWidgets.QCheckBox(Dialog)
        self.de_phalanx.setGeometry(QtCore.QRect(360, 280, 70, 17))
        self.de_phalanx.setObjectName("de_phalanx")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(360, 350, 91, 16))
        self.label_8.setObjectName("label_8")
        self.de_immune = QtWidgets.QPlainTextEdit(Dialog)
        self.de_immune.setGeometry(QtCore.QRect(360, 370, 171, 31))
        self.de_immune.setObjectName("de_immune")
        self.de_except = QtWidgets.QPlainTextEdit(Dialog)
        self.de_except.setGeometry(QtCore.QRect(360, 420, 171, 31))
        self.de_except.setObjectName("de_except")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(360, 400, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(120, 480, 91, 16))
        self.label_10.setObjectName("label_10")
        self.spells = QtWidgets.QPlainTextEdit(Dialog)
        self.spells.setGeometry(QtCore.QRect(120, 500, 171, 51))
        self.spells.setObjectName("spells")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(360, 450, 91, 16))
        self.label_11.setObjectName("label_11")
        self.tags = QtWidgets.QPlainTextEdit(Dialog)
        self.tags.setGeometry(QtCore.QRect(360, 470, 171, 31))
        self.tags.setObjectName("tags")
        self.plainText_move = QtWidgets.QLineEdit(Dialog)
        self.plainText_move.setGeometry(QtCore.QRect(70, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.plainText_move.setFont(font)
        self.plainText_move.setAlignment(QtCore.Qt.AlignCenter)
        self.plainText_move.setObjectName("plainText_move")
        self.plainText_at = QtWidgets.QLineEdit(Dialog)
        self.plainText_at.setGeometry(QtCore.QRect(110, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.plainText_at.setFont(font)
        self.plainText_at.setAlignment(QtCore.Qt.AlignCenter)
        self.plainText_at.setObjectName("plainText_at")
        self.plainText_de = QtWidgets.QLineEdit(Dialog)
        self.plainText_de.setGeometry(QtCore.QRect(150, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.plainText_de.setFont(font)
        self.plainText_de.setAlignment(QtCore.Qt.AlignCenter)
        self.plainText_de.setObjectName("plainText_de")
        self.plainText_bp = QtWidgets.QLineEdit(Dialog)
        self.plainText_bp.setGeometry(QtCore.QRect(190, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.plainText_bp.setFont(font)
        self.plainText_bp.setAlignment(QtCore.Qt.AlignCenter)
        self.plainText_bp.setObjectName("plainText_bp")
        self.plainText_mp = QtWidgets.QLineEdit(Dialog)
        self.plainText_mp.setGeometry(QtCore.QRect(230, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HQModern")
        font.setPointSize(12)
        self.plainText_mp.setFont(font)
        self.plainText_mp.setAlignment(QtCore.Qt.AlignCenter)
        self.plainText_mp.setObjectName("plainText_mp")
        self.group_box_style.raise_()
        self.group_box_de_symbol.raise_()
        self.group_box_at_symbol.raise_()
        self.buttonBox.raise_()
        self.graphic_background.raise_()
        self.textEdit_name.raise_()
        self.graphicsView.raise_()
        self.label_move.raise_()
        self.label_at.raise_()
        self.label_de.raise_()
        self.label_bp.raise_()
        self.label_mp.raise_()
        self.plain_text_special_rules.raise_()
        self.at_diagonal.raise_()
        self.at_ranged.raise_()
        self.icon_topleft.raise_()
        self.icon_bottomright.raise_()
        self.at_number.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.at_damage_type.raise_()
        self.de_guardian.raise_()
        self.de_master.raise_()
        self.de_phalanx.raise_()
        self.label_8.raise_()
        self.de_immune.raise_()
        self.de_except.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.spells.raise_()
        self.label_11.raise_()
        self.tags.raise_()
        self.plainText_move.raise_()
        self.plainText_at.raise_()
        self.plainText_de.raise_()
        self.plainText_bp.raise_()
        self.plainText_mp.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Monster Editor"))
        self.textEdit_name.setToolTip(_translate("Dialog", "Change the model\'s name here"))
        self.textEdit_name.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gaze\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Swordsman</p></body></html>"))
        self.graphicsView.setToolTip(_translate("Dialog", "Double click to load an image"))
        self.graphicsView.setStatusTip(_translate("Dialog", "Double click here to choose a picture"))
        self.label_move.setText(_translate("Dialog", "Move"))
        self.label_at.setText(_translate("Dialog", "AT"))
        self.label_de.setText(_translate("Dialog", "DE"))
        self.label_bp.setText(_translate("Dialog", "BP"))
        self.label_mp.setText(_translate("Dialog", "MP"))
        self.plain_text_special_rules.setToolTip(_translate("Dialog", "Type your special rule in this area"))
        self.plain_text_special_rules.setPlainText(_translate("Dialog", "No special rules"))
        self.group_box_style.setStatusTip(_translate("Dialog", "Click here to switch between EU and US style cards"))
        self.group_box_style.setTitle(_translate("Dialog", "Style"))
        self.radio_us.setToolTip(_translate("Dialog", "Click here for US style layout"))
        self.radio_us.setText(_translate("Dialog", "US"))
        self.radio_eu.setToolTip(_translate("Dialog", "Click here for EU style layout"))
        self.radio_eu.setText(_translate("Dialog", "EU"))
        self.at_diagonal.setToolTip(_translate("Dialog", "This model may attack diagonal standing figures."))
        self.at_diagonal.setStatusTip(_translate("Dialog", "This model may attack diagonal standing enemies."))
        self.at_diagonal.setText(_translate("Dialog", "Diagonal"))
        self.at_ranged.setToolTip(_translate("Dialog", "This model may attack at range."))
        self.at_ranged.setStatusTip(_translate("Dialog", "This model may make ranged attacks."))
        self.at_ranged.setText(_translate("Dialog", "Ranged"))
        self.group_box_at_symbol.setTitle(_translate("Dialog", "AT Symbol"))
        self.radio_at_skull.setToolTip(_translate("Dialog", "Attacks on Skulls"))
        self.radio_at_skull.setText(_translate("Dialog", "AT on skull"))
        self.radio_at_shield.setToolTip(_translate("Dialog", "Attacks on Shields"))
        self.radio_at_shield.setText(_translate("Dialog", "AT on Shield"))
        self.radio_at_walrus.setToolTip(_translate("Dialog", "Attacks on Walrus"))
        self.radio_at_walrus.setText(_translate("Dialog", "AT on Walrus"))
        self.icon_topleft.setToolTip(_translate("Dialog", "Double click to change the symbol"))
        self.icon_topleft.setStatusTip(_translate("Dialog", "double click here to choose an icon"))
        self.icon_bottomright.setToolTip(_translate("Dialog", "Double Click to change the symbol"))
        self.icon_bottomright.setStatusTip(_translate("Dialog", "double click here to choose an icon"))
        self.group_box_de_symbol.setTitle(_translate("Dialog", "DE Symbol"))
        self.radio_de_skull.setToolTip(_translate("Dialog", "Defends on Skulls"))
        self.radio_de_skull.setText(_translate("Dialog", "DE on skull"))
        self.radio_de_shield.setToolTip(_translate("Dialog", "Defends on Shields"))
        self.radio_de_shield.setText(_translate("Dialog", "DE on Shield"))
        self.radio_de_walrus.setToolTip(_translate("Dialog", "Defends on Walruses"))
        self.radio_de_walrus.setText(_translate("Dialog", "DE on Walrus"))
        self.at_number.setToolTip(_translate("Dialog", "How many attacks does this model have per turn?"))
        self.label_6.setText(_translate("Dialog", "AT Number"))
        self.label_7.setText(_translate("Dialog", "AT damage type"))
        self.at_damage_type.setToolTip(_translate("Dialog", "Enter some damage type here, like fire, magic, poison...\n"
" if there are several damage types, enter them comma separated.\n"
"It\'s completely optional, except that some rare game \n"
"cards react on that (\"heals 2 BP damage from poison\")"))
        self.de_guardian.setToolTip(_translate("Dialog", "If this model rolls two success symbols during defense, \n"
"all the attack damage is negated."))
        self.de_guardian.setStatusTip(_translate("Dialog", "If two or more defense dice show the right symbol, all damage is negated."))
        self.de_guardian.setText(_translate("Dialog", "Guardian"))
        self.de_master.setToolTip(_translate("Dialog", "If this model rolls a single success symbols during defense, \n"
"all the attack damage is negated."))
        self.de_master.setStatusTip(_translate("Dialog", " If a single defense die shows the right symbol, all damage is negated."))
        self.de_master.setText(_translate("Dialog", "Master"))
        self.de_phalanx.setToolTip(_translate("Dialog", "If two or more models with this rule are in the same room,\n"
"they all get one defense die more. This assumes that the\n"
"controlling player knows how to play for activating this rule."))
        self.de_phalanx.setStatusTip(_translate("Dialog", "If several models with \"phalanx\" are in the same room, they all get one white die more for defense. Assuming their player knows how to play this rule."))
        self.de_phalanx.setText(_translate("Dialog", "Phalanx"))
        self.label_8.setText(_translate("Dialog", "Immune to:"))
        self.de_immune.setToolTip(_translate("Dialog", "Enter some comma separated words here. The model is \n"
"immune to this damage. \"all\" means it is invulnerable. \n"
"Should be the same words like AT damage type."))
        self.de_except.setToolTip(_translate("Dialog", "If you entered \"all\" in immune, you may enter exceptions \n"
"here. Immune: all and Except for magic, that means a \n"
"model can be harmed only by magic."))
        self.label_9.setText(_translate("Dialog", "Except for:"))
        self.label_10.setText(_translate("Dialog", "List of Spells:"))
        self.spells.setToolTip(_translate("Dialog", "If this model can use spells, enter them here.\n"
" It will be displayed in the quest monster table."))
        self.label_11.setText(_translate("Dialog", "Tags:"))
        self.tags.setToolTip(_translate("Dialog", "put as many comma separated tags here as you like. \n"
"This helps filtering the monster list in the editor; it also \n"
"helps targeting for some ingame effects (\"Undead models \n"
"are immune to this spell\") Tags used today are:\n"
"\n"
"Green, Undead, Chaos, Demon, Human, Special, Ogre, \n"
"Sorcerer, Hero, Ice, Boss, Man-at-Arms, Elf, Beast, \n"
"Soldier, Dragon, Golem, Skaven, Troll, Dwarf, Base, KK, \n"
"Rotlw, ATOH, WOM (or woz), BQP, DarkCompany, EQP."))
        self.plainText_move.setToolTip(_translate("Dialog", "Enter the move value here"))
        self.plainText_move.setText(_translate("Dialog", "6"))
        self.plainText_at.setToolTip(_translate("Dialog", "Enter the AT value here"))
        self.plainText_at.setText(_translate("Dialog", "2"))
        self.plainText_de.setToolTip(_translate("Dialog", "Enter the DE value here"))
        self.plainText_de.setText(_translate("Dialog", "2"))
        self.plainText_bp.setToolTip(_translate("Dialog", "Enter the BP here"))
        self.plainText_bp.setText(_translate("Dialog", "1"))
        self.plainText_mp.setToolTip(_translate("Dialog", "Enter the MP here"))
        self.plainText_mp.setText(_translate("Dialog", "0"))

